### PR TITLE
Changes skin colour

### PR DESCRIPTION
**Pull request by Kraseo**
shamelessly recoloured from eris

imagen
imagen

### CODE REVIEW

**Comment by OrangeMann** [comment]
No thanks

**Comment by Kraseo** [comment]
humans have always looked like they suffer from constant liver poisoning and I think matt would rather have this

**Comment by mattroks101** [comment]
This is just the same sprites recolored correct? You didn't change the sprites otherwise?

**Comment by Kraseo** [comment]
yeah, sprites are all just recoloured to eris' pallette

**Comment by mattroks101** [comment]
Ok we'll try this out, see how it looks.

**Pull request merged**
