### PR TITLE
Changes cargo shuttle sprites

### PR DESCRIPTION
**Pull request by joctopus**
old
old
now
now

### CODE REVIEW

**Comment by joctopus** [comment]
>8 commits
i'm forgot abut branches whoops

**Comment by Kraseo** [comment]
SWITCH 👏 YOUR 👏 BRANCH 👏 WHEN 👏 YOU 👏 WORK

**Comment by mattroks101** [comment]
Is this good to go?

**Comment by joctopus** [comment]
@mattroks101 yep.

**Comment by joctopus** [comment]
@Kraseo i know meh

**Pull request merged**
